name = "tubepulse-cron"
main = "index.js"
compatibility_date = "2025-04-01"
account_id = "93e62acb204fe695139d8441880ed4a3"

[[kv_namespaces]]
binding = "TUBEPULSE_KV"
id = "f2ac3fd3ae9c457287074e7e32c66c64"

[triggers]
crons = ["*/2 * * * *"]

[observability]
enabled = true